[tool.ruff]
exclude = [
    '.git',
    'docs',
    'setup.py',
]
line-length = 79
lint.ignore = [
    "D213",
    "D203",
]
lint.select = [
    "E",
    "F",
    "W",
    "D",
]
lint.preview = true

# Ignore missing docstrings in tests
[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D103",
    "D104",
]
